# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-09 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
